services:
    apcs_tool:
        image: littleorange666/apcs_tool:1.1.11
        restart: on-failure
        healthcheck:
          test: ["CMD", "python3", "-c", "import http.client; c=http.client.HTTPConnection('localhost', 8070); c.request('GET', '/health_check'); r=c.getresponse(); exit(0) if r.status < 400 else exit(1)"]
          interval: 10s
          start_period: 10s
          timeout: 3s
          retries: 5
        environment:
          - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
          - QingdaoUOJ_URL=https://apcs-simulation.com
          - QingdaoUOJ_ACCOUNT=${QingdaoUOJ_ACCOUNT}
          - QingdaoUOJ_PASSWORD=${QingdaoUOJ_PASSWORD}
          - ORANGEJUDGE_URL=${ORANGEJUDGE_URL}
          - ORANGEJUDGE_USERNAME=${ORANGEJUDGE_USERNAME}
          - ORANGEJUDGE_API_KEY=${ORANGEJUDGE_API_KEY}
          - OUTPUT_LIMIT=10
        dns:
          - 8.8.8.8
          - 8.8.4.4
        volumes:
          - ./data:/app/data
    cloudflared:
        image: cloudflare/cloudflared:latest
        command: tunnel --url http://apcs_tool:8070 --no-autoupdate run
        restart: unless-stopped
        depends_on:
          apcs_tool:
           condition: service_healthy
        environment:
          - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}